/*
 * Auto-generated by Frida. Please modify to match the signature of Sleep.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('Intercepted Sleep! Skipping delay...');
    args[0] = ptr(0); // Set sleep time to 0
  },

  onLeave(log, retval, state) {
  }
});
